In [7]:
import numpy as np
import pandas as pd

newData = pd.read_csv("/content/housing.csv")
newData

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [13]:
df = pd.DataFrame(newData)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [14]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [15]:
df['ocean_proximity'].nunique()

5

In [18]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [22]:
mean_total_bedroom = df['total_bedrooms'].mean()
mean_total_bedroom

537.8705525375618

In [23]:
df['total_bedrooms'].fillna(mean_total_bedroom)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [24]:
mean_total_bedroom2 = df['total_bedrooms'].mean()
mean_total_bedroom2

537.8705525375618

In [31]:
islandData = df[df['ocean_proximity'] == 'ISLAND']
islandData

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [37]:
q7 = islandData[['housing_median_age', 'total_rooms', 'total_bedrooms']]
q7

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [58]:
x = q7.to_numpy()
x

xs = np.transpose(x)
xs

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [59]:
XTX = x.dot(xs)
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [52]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [54]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[-3.94698363e+08,  2.39473542e+08, -8.50273505e+07,
        -7.37257115e+08,  1.41251806e+09],
       [ 3.12774609e+08,  4.73094498e+08, -6.47616534e+08,
         9.65765382e+08, -1.70998512e+09],
       [-1.64093392e+08, -6.15435935e+08,  7.35878869e+08,
        -7.18050534e+08,  1.22434885e+09],
       [-6.95066147e+08,  8.03247975e+08, -5.61274135e+08,
        -1.07870922e+09,  2.14748365e+09],
       [ 1.34720249e+09, -1.40803192e+09,  9.27322484e+08,
         2.17647067e+09, -4.29496730e+09]])

In [60]:
wresult = xs.dot(XTX_inv)
wresult


array([[-8.86321068e-03, -1.43151283e-02,  6.33513927e-03,
         1.98273659e-02,  2.14843750e-02],
       [-2.25162506e-03,  2.57301331e-03, -3.33786011e-06,
        -1.24549866e-03, -4.88281250e-04],
       [ 9.17005539e-03, -6.57939911e-03, -1.45697594e-03,
         3.45897675e-03, -2.44140625e-04]])

In [61]:
w = y * wresult
w

array([[-8.42005014e+00, -1.86096668e+01,  5.06811142e+00,
         1.98273659e+01,  2.79296875e+01],
       [-2.13904381e+00,  3.34491730e+00, -2.67028809e-03,
        -1.24549866e+00, -6.34765625e-01],
       [ 8.71155262e+00, -8.55321884e+00, -1.16558075e+00,
         3.45897675e+00, -3.17382812e-01]])